"""Add player posicao pe and modify posicao column

Revision ID: 20260424_add_player_posicao_pe
Revises: add_player_details
Create Date: 2026-04-24 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260424_add_player_posicao_pe'
down_revision: Union[str, None] = 'add_player_details'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Modificar coluna posicao de String(100) para String(50)
    op.alter_column('players', 'posicao', existing_type=sa.String(100), type_=sa.String(50))
    # Adicionar coluna pe
    op.add_column('players', sa.Column('pe', sa.String(1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pe')
    # Revert posicao column back to String(100)
    op.alter_column('players', 'posicao', existing_type=sa.String(50), type_=sa.String(100))
    # ### end Alembic commands ###
