"""Adding invite_token_expires to user

Revision ID: 274e25eec915
Revises: cebe474a2954
Create Date: 2025-10-30 02:09:03.321281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274e25eec915'
down_revision: Union[str, None] = 'cebe474a2954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invite_token_expires')
    # ### end Alembic commands ###
