"""Add suspension types

Revision ID: 3b372a5a0f80
Revises: 4367d373ab57
Create Date: 2026-05-01 22:21:16.013949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b372a5a0f80'
down_revision: Union[str, None] = '4367d373ab57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_admin_actions_admin_id', table_name='player_admin_actions')
    op.drop_index('ix_player_admin_actions_player_id', table_name='player_admin_actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_admin_actions_player_id', 'player_admin_actions', ['player_id'], unique=False)
    op.create_index('ix_player_admin_actions_admin_id', 'player_admin_actions', ['admin_id'], unique=False)
    # ### end Alembic commands ###
