"""Add suspension types

Revision ID: 4367d373ab57
Revises: player_admin_actions_001
Create Date: 2026-05-01 22:11:31.108472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4367d373ab57'
down_revision: Union[str, None] = 'player_admin_actions_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_admin_actions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('player_admin_actions', 'action_type',
               existing_type=sa.Enum('SUSPEND', 'FINE', 'BLOCK', 'UNBLOCK', 'OBSERVE', name='adminactiontypeenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('player_admin_actions', 'is_indefinite')
    op.drop_column('player_admin_actions', 'suspension_matches')
    # ### end Alembic commands ###
