"""init

Revision ID: 94350a4c7d03
Revises: 
Create Date: 2026-03-24 18:38:56.523631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94350a4c7d03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id_season', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('initial_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_season')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=False),
    sa.Column('setup_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invite_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('event_score_rules',
    sa.Column('id_event_score_rule', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ROUND_WINNER', 'MVP', 'WORST_PLAYER', 'BEST_GOAL', 'BEST_DEFENSE', 'TOAST', 'UNBELIVABLE', 'BEST_GOAL_KEEPER', 'ROULETTE', 'GOAL', 'ASSIST', 'BLUNDER', 'YELLOW_CARD', 'RED_CARD', 'OWN_GOAL', 'HOME_WIN', 'AWAY_WIN', 'DRAW', name='eventtypeenum'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('context', sa.Enum('MATCH', 'ROUND', 'SEASON', name='eventcontextenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id_season'], ),
    sa.PrimaryKeyConstraint('id_event_score_rule')
    )
    op.create_table('players',
    sa.Column('id_player', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_associate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_player')
    )
    op.create_table('round',
    sa.Column('id_round', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('referee', sa.String(length=255), nullable=False),
    sa.Column('initial_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id_season'], ),
    sa.PrimaryKeyConstraint('id_round')
    )
    op.create_table('awards',
    sa.Column('id_award', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ROUND_WINNER', 'MVP', 'WORST_PLAYER', 'BEST_GOAL', 'BEST_DEFENSE', 'TOAST', 'UNBELIVABLE', 'BEST_GOAL_KEEPER', 'ROULETTE', 'GOAL', 'ASSIST', 'BLUNDER', 'YELLOW_CARD', 'RED_CARD', 'OWN_GOAL', 'HOME_WIN', 'AWAY_WIN', 'DRAW', name='eventtypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id_round'], ),
    sa.PrimaryKeyConstraint('id_award')
    )
    op.create_table('player_scores',
    sa.Column('id_player_score', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('points_individual', sa.Integer(), nullable=False),
    sa.Column('points_team', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id_player'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id_round'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id_season'], ),
    sa.PrimaryKeyConstraint('id_player_score')
    )
    op.create_table('player_season_scores',
    sa.Column('id_player_season_score', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id_player'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id_season'], ),
    sa.PrimaryKeyConstraint('id_player_season_score')
    )
    op.create_table('teams',
    sa.Column('id_team', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id_round'], ),
    sa.PrimaryKeyConstraint('id_team')
    )
    op.create_table('award_players',
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id_award'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id_player'], ),
    sa.PrimaryKeyConstraint('award_id', 'player_id')
    )
    op.create_table('award_teams',
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id_award'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id_team'], ),
    sa.PrimaryKeyConstraint('award_id', 'team_id')
    )
    op.create_table('matches',
    sa.Column('id_match', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('filmed_by', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ROUND_WINNER', 'MVP', 'WORST_PLAYER', 'BEST_GOAL', 'BEST_DEFENSE', 'TOAST', 'UNBELIVABLE', 'BEST_GOAL_KEEPER', 'ROULETTE', 'GOAL', 'ASSIST', 'BLUNDER', 'YELLOW_CARD', 'RED_CARD', 'OWN_GOAL', 'HOME_WIN', 'AWAY_WIN', 'DRAW', name='eventtypeenum'), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=False),
    sa.Column('score_away', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id_team'], ),
    sa.ForeignKeyConstraint(['filmed_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id_team'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id_round'], ),
    sa.PrimaryKeyConstraint('id_match')
    )
    op.create_table('team_players',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id_player'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id_team'], ),
    sa.PrimaryKeyConstraint('team_id', 'player_id')
    )
    op.create_table('match_events',
    sa.Column('id_event', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ROUND_WINNER', 'MVP', 'WORST_PLAYER', 'BEST_GOAL', 'BEST_DEFENSE', 'TOAST', 'UNBELIVABLE', 'BEST_GOAL_KEEPER', 'ROULETTE', 'GOAL', 'ASSIST', 'BLUNDER', 'YELLOW_CARD', 'RED_CARD', 'OWN_GOAL', 'HOME_WIN', 'AWAY_WIN', 'DRAW', name='eventtypeenum'), nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id_match'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id_player'], ),
    sa.PrimaryKeyConstraint('id_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_events')
    op.drop_table('team_players')
    op.drop_table('matches')
    op.drop_table('award_teams')
    op.drop_table('award_players')
    op.drop_table('teams')
    op.drop_table('player_season_scores')
    op.drop_table('player_scores')
    op.drop_table('awards')
    op.drop_table('round')
    op.drop_table('players')
    op.drop_table('event_score_rules')
    op.drop_table('users')
    op.drop_table('seasons')
    # ### end Alembic commands ###
