"""Add player details: apelido, email, telefone, posicao, potes, is_guest

Revision ID: add_player_details
Revises: add_is_active_seasons
Create Date: 2026-04-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_player_details'
down_revision: Union[str, None] = 'add_is_active_seasons'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('apelido', sa.String(255), nullable=True))
    op.add_column('players', sa.Column('email', sa.String(255), nullable=True))
    op.add_column('players', sa.Column('telefone', sa.String(20), nullable=True))
    op.add_column('players', sa.Column('posicao', sa.String(100), nullable=True))
    op.add_column('players', sa.Column('potes', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('is_guest', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_guest')
    op.drop_column('players', 'potes')
    op.drop_column('players', 'posicao')
    op.drop_column('players', 'telefone')
    op.drop_column('players', 'email')
    op.drop_column('players', 'apelido')
    # ### end Alembic commands ###
