"""Default updated_at timestamp

Revision ID: cebe474a2954
Revises: f29da6be6aea
Create Date: 2025-10-29 20:14:36.234114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebe474a2954'
down_revision: Union[str, None] = 'f29da6be6aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE event_score_rules MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE match_events MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE matches MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE player_scores MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE player_season_scores MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE players MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE round MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE seasons MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
        ALTER TABLE teams MODIFY updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users MODIFY updated_at DATETIME NULL;
        ALTER TABLE event_score_rules MODIFY updated_at DATETIME NULL;
        ALTER TABLE match_events MODIFY updated_at DATETIME NULL;
        ALTER TABLE matches MODIFY updated_at DATETIME NULL;
        ALTER TABLE player_scores MODIFY updated_at DATETIME NULL;
        ALTER TABLE player_season_scores MODIFY updated_at DATETIME NULL;
        ALTER TABLE players MODIFY updated_at DATETIME NULL;
        ALTER TABLE round MODIFY updated_at DATETIME NULL;
        ALTER TABLE seasons MODIFY updated_at DATETIME NULL;
        ALTER TABLE teams MODIFY updated_at DATETIME NULL;
    """)
    # ### end Alembic commands ###
