"""create initial tables

Revision ID: f29da6be6aea
Revises: f4ca1bbf0eaa
Create Date: 2025-10-29 15:43:49.639027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29da6be6aea'
down_revision: Union[str, None] = 'f4ca1bbf0eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
